markdown: kramdown
permalink: /:categories/:title.html
url: 
highlighter: true
safe: true
# auto: true 
# presonal config
domain: www.itskys.com
title: itskys.com
description: Network, Linux, Servers, Java, Android, iOS, reading...
author: Kingkong
email: itskys#gmail.com
github: itskys

config:
  js_dir:
  img_dir:
  css_dir:
